# Generated by Django 4.1 on 2022-08-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.ImageField(upload_to='posts/'),
        ),
    ]
