# Generated by Django 4.1 on 2022-08-25 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0008_alter_post_liked_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-updated_at', '-pk']},
        ),
    ]
