# Generated by Django 4.1 on 2022-09-27 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0013_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="comment",
        ),
    ]
