# Generated by Django 4.1 on 2022-09-27 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0014_rename_content_comment_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="postapp.post",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("post__isnull", True),
                        ("replied_to__isnull", True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("post__isnull", False),
                        ("replied_to__isnull", False),
                        _connector="OR",
                    ),
                ),
                name="post_xor_replied_to",
            ),
        ),
    ]
