# Generated by Django 4.1 on 2022-09-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0016_remove_comment_post_xor_replied_to_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment",
            name="post_xor_replied_to",
        ),
        migrations.AddConstraint(
            model_name="comment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("post__isnull", True),
                        ("replied_to__isnull", True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("post__isnull", False),
                        ("replied_to__isnull", False),
                        _connector="OR",
                    ),
                ),
                name="post_xor_replied_to",
                violation_error_message="Comment must be either a reply or a post comment, not Both",
            ),
        ),
    ]
