# Generated by Django 4.1 on 2022-09-30 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0018_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="url",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
    ]
