# Generated by Django 4.1 on 2022-10-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0020_post_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(blank=True, null=True),
        ),
    ]
