# Generated by Django 4.1 on 2022-10-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0021_alter_post_caption"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("url__isnull", False), ("caption__isnull", False), _connector="OR"
                ),
                name="url_or_caption",
            ),
        ),
    ]
