# Generated by Django 4.1 on 2022-10-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0022_post_url_or_caption"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="post",
            name="url_or_caption",
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("url__isnull", True),
                        ("caption__isnull", True),
                        _connector="OR",
                    ),
                    _negated=True,
                ),
                name="url_or_caption",
            ),
        ),
    ]
