# Generated by Django 4.1 on 2022-10-03 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0023_remove_post_url_or_caption_post_url_or_caption"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="post",
            name="url_or_caption",
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("caption__isnull", True), ("url__isnull", True), _negated=True
                ),
                name="url_or_caption",
            ),
        ),
    ]
