# Generated by Django 4.1 on 2022-10-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0026_alter_post_caption"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="post",
            name="url_or_caption",
        ),
        migrations.AlterField(
            model_name="post",
            name="caption",
            field=models.TextField(default="", null=True),
        ),
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("url__isnull", True), ("caption__isnull", True), _negated=True
                ),
                name="url_or_caption",
                violation_error_message="Post must have either a url or a caption",
            ),
        ),
    ]
