# Generated by Django 4.1 on 2022-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0031_remove_post_url_or_caption_post_url_or_caption"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="post",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("caption__exact", ""), ("url__exact", ""), _connector="OR"
                    ),
                    _negated=True,
                ),
                name="url_or_caption",
                violation_error_message="Post must have either a url or a caption",
            ),
        ),
    ]
