# Generated by Django 4.1 on 2023-03-06 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="keyring",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.RemoveField(
            model_name="message",
            name="read",
        ),
        migrations.DeleteModel(
            name="Chat",
        ),
        migrations.DeleteModel(
            name="KeyRing",
        ),
    ]
