# Generated by Django 4.1 on 2023-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_group",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="chat",
            name="dp",
            field=models.ImageField(
                blank=True, default="../static/authn/dp.png", upload_to="chat/dp"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
