# Generated by Django 4.1 on 2023-02-20 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_chat_is_group_alter_chat_dp_alter_chat_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-created"]},
        ),
        migrations.RemoveField(
            model_name="message",
            name="read",
        ),
        migrations.RemoveField(
            model_name="message",
            name="to_user",
        ),
        migrations.AlterField(
            model_name="message",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
