# Generated by Django 4.1 on 2023-03-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_remove_keyring_user_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
    ]
