# Generated by Django 4.1 on 2022-08-12 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
    ]
