# Generated by Django 4.1 on 2022-09-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0003_user_bio_user_cover_user_dp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, default="Add Bio", null=True),
        ),
    ]
