# Generated by Django 4.1 on 2022-09-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0004_alter_user_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cover",
            field=models.ImageField(
                blank=True, default="/static/authn/cover.png", upload_to="covers/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="dp",
            field=models.ImageField(
                blank=True, default="/static/authn/dp.png", upload_to="dp/"
            ),
        ),
    ]
