# Generated by Django 4.1 on 2022-09-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0005_alter_user_cover_alter_user_dp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="dp",
            field=models.ImageField(
                blank=True, default="../static/authn/dp.png", upload_to="dp/"
            ),
        ),
    ]
