# Generated by Django 4.1 on 2022-09-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0006_alter_user_dp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="cover",
            field=models.ImageField(
                blank=True, default="../static/authn/cover.png", upload_to="covers/"
            ),
        ),
    ]
