# Generated by Django 4.1 on 2022-10-03 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authn", "0010_alter_user_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("-date_joined",)},
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
