# Generated by Django 4.1 on 2022-10-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("postapp", "0034_remove_post_url_or_caption_post_url_or_caption"),
        ("notifzz", "0002_remove_notification_user_notification_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="postapp.post",
            ),
        ),
    ]
