# Generated by Django 4.1 on 2023-02-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifzz", "0003_alter_notification_post"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={"ordering": ["-date"]},
        ),
    ]
