on:
 push:
   branches: [main,master]
 workflow_dispatch:
  
  

jobs:
  deploy:
    runs-on: ubuntu-latest
  
    steps:
      - name: SSH Command
        uses: D3rHase/ssh-command-action@v0.2.2
        
        with:
          
          host: 3.111.252.41
          port: 22 # optional, default is 22
          user: ${{secrets.CD_USER }}
          private_key: ${{secrets.CD_SSH_PRIVATE }}
          
          command: cd winbookBackend; git pull; docker-compose up -d --build;cd ..


   
   
